const resep = [
  {
    id: 1,
    title:
      "Ayam Recheese",
    image:
      "https://i.pinimg.com/474x/b3/03/b8/b303b87f4e5cee074a1c2325decbefe9.jpg",
    ingredients: [
      "ayam",
      "bawang putih",
      "bawang merah",
      "lada bubuk",
      "garam",
      "kaldu ayam bubuk",
      "tepung ayam crispy",
      "tepung maizena",
      "air dingin",
      "saus sambal",
      "saus tomat",
      "gula merah",
      "saus tiram",
      "cuka",
      "bubuk cabai untuk saus pedas",
    ],
    steps: [
      "Siapkan 5 potong ayam yang sudah dicuci bersih.",
      "Haluskan bawang putih dan bawang merah.",
      "Tambahkan lada bubuk, garam, dan kaldu ayam bubuk. Balurkan bumbu halus pada ayam secara merata dan diamkan selama 15 menit agar bumbu meresap.",
      "Campurkan tepung ayam crispy dan tepung maizena ke dalam dua wadah berbeda.",
      "Balurkan ayam pada tepung kering pertama, kemudian celupkan secara perlahan ayam tersebut dengan air dingin.",
      "Balurkan ayam pada tepung kering kedua hingga tebal.",
      "Goreng ayam yang telah ditepungi pada minyak panas hingga berwarna coklat keemasan.",
      "Angkat dan tiriskan ayam.",
      "Untuk saus pedas, tumis bawang putih dengan minyak. Tambahkan saus sambal, saus tomat, gula merah, saus tiram, cuka, dan bubuk cabai. Aduk hingga merata dan masak hingga matang.",
      "Sajikan ayam recheese dengan saus pedas.",
    ],
    kalori: 10000,
  },
  {
    id: 2,
    title: "Nasi Goreng Udang",
    image: "https://i.pinimg.com/474x/2c/e9/5c/2ce95c1a8a71282015ac012e246e4688.jpg",
    ingredients: [
      "Nasi",
      "Udang",
      "Bawang putih",
      "Bawang merah",
      "Lada bubuk",
      "Garam",
      "Kaldu ayam bubuk",
      "Saus sambal",
      "Saus tomat",
      "Gula merah",
      "Saus tiram",
      "Cuka",
      "Bubuk cabai untuk saus pedas",
    ],
    steps: [
      "Siapkan nasi yang sudah dingin.",
      "Panaskan minyak di wajan.",
      "Tumis bawang putih dan bawang merah hingga harum.",
      "Masukkan udang, aduk hingga berubah warna.",
      "Tambahkan nasi, lada bubuk, garam, dan kaldu ayam bubuk. Aduk rata.",
      "Masukkan saus sambal, saus tomat, gula merah, saus tiram, cuka, dan bubuk cabai. Aduk hingga merata.",
      "Masak hingga semua bahan tercampur dan nasi agak kering.",
      "Angkat dan sajikan nasi goreng udang dalam piring saji.",
      "Nasi goreng udang siap dinikmati!",
    ],
    kalori: 700,
  },
  {
    id: 3,
    title: "Soto Jakarta",
    image: "https://i.pinimg.com/474x/1d/e4/a1/1de4a19e2d70724d71ad912cec05885d.jpg",
    ingredients: [
      "500g ayam, potong menjadi 5 bagian",
      "3 siung bawang putih, haluskan",
      "2 buah bawang merah, haluskan",
      "1 sendok teh lada bubuk",
      "1 sendok teh garam",
      "2 sendok teh kaldu ayam bubuk",
      "Tepung ayam crispy",
      "Tepung maizena",
      "Air dingin",
      "Saus sambal",
      "Saus tomat",
      "2 batang serai, memarkan",
      "2 lembar daun salam",
      "2 lembar daun jeruk",
      "1 ruas jahe, memarkan",
      "3 liter air",
      "Bawang goreng, untuk taburan",
      "Ketupat, untuk pelengkap"
    ],
    steps: [
      "Siapkan 500g ayam yang sudah dicuci bersih.",
      "Haluskan bawang putih dan bawang merah.",
      "Tambahkan lada bubuk, garam, dan kaldu ayam bubuk. Balurkan bumbu halus pada ayam secara merata dan diamkan selama 15 menit agar bumbu meresap.",
      "Campurkan tepung ayam crispy dan tepung maizena ke dalam dua wadah berbeda.",
      "Balurkan ayam pada tepung kering pertama, kemudian celupkan secara perlahan ayam tersebut dengan air dingin.",
      "Balurkan ayam pada tepung kering kedua hingga tebal.",
      "Goreng ayam yang telah ditepungi pada minyak panas hingga berwarna coklat keemasan.",
      "Angkat dan tiriskan ayam.",
      "Siapkan panci besar, masukkan air, serai, daun salam, daun jeruk, dan jahe. Rebus hingga mendidih.",
      "Masukkan ayam yang sudah digoreng ke dalam rebusan air. Masak hingga ayam matang dan kuahnya bercita rasa.",
      "Sajikan soto Jakarta dalam mangkuk saji. Taburi dengan bawang goreng dan sajikan dengan ketupat.",
    ],
    kalori: 780,
  },  
  {
    id: 4,
    title: "Sando",
    image:
      "https://i.pinimg.com/474x/97/7d/34/977d34aa03d0e7f89458094da06e5f65.jpg",
        ingredients: [
          "2 buah kiwi kecil, kupas dan belah dua memanjang",
          "8 stroberi berukuran kecil hingga sedang, belah dua memanjang",
          "1 buah mangga, potong menjadi 16 bagian",
          "1 cangkir whipping cream kental dingin",
          "1 1/2 sendok makan gula",
          "1/4 sendok teh ekstrak vanila (vanili)",
          "Delapan irisan roti tawar dengan tebal sekitar 1,5cm."
        ],
        steps: [
          "Kocok whipping cream, gula, dan vanili dalam sebuah mangkuk besar hingga hampir kaku.",
          "Letakkan empat irisan roti tawar di atas talenan dalam dua baris, lalu oleskan seperdelapan whipping cream secara merata pada setiap irisan.",
          "Lalu, letakkan setengah potong buah kiwi di bagian tengah bawah, setengah stroberi di setiap sudut bawah roti dengan ujung batang menghadap kiwi, dan sepotong mangga di tengah-tengah kiwi dan stroberi.",
          "Setelah itu, tutupi setiap sandwich dengan salah satu irisan roti bagian atas dengan sisi mengandung krim menghadap ke bawah.",
          "Bungkus setiap sandwich menggunakan plastic wrap dengan rapat dan hati-hati, lalu tekan-tekan sedikit dengan tangan.",
          "Dinginkan dalam lemari es selama 2-8 jam.",
          "Buka bungkus sandwich dan potong bagian tepinya dengan pisau bergerigi, lalu potong sandwich menjadi dua secara diagonal.",
          "Fruit Sando alias sandwich buah ala Jepang pun siap disajikan!"
        ],
    kalori:100,
  },
  {
    id: 5,
    title:
      "Mie Nyemek",
    image:
      "https://i.pinimg.com/474x/00/25/e6/0025e671ee7dfa275f8a6c68d41ad4b9.jpg",
    ingredients: [
          "2 bungkus mie instan goreng",
          "Aneka bakso (opsional)",
          "1 butir telur",
          "Bumbu:",
          "2 siung bawang merah",
          "2 siung bawang putih",
          "Cabai rawit secukupnya",
          "1 batang daun bawang",
          "Saus sambal secukupnya",
          "Kecap manis secukupnya"
        ],
        steps: [
          "Siapkan semua bahan dan bumbu hingga lengkap.",
          "Tumis bumbu iris hingga wangi dan matang, tambahkan 1 butir telur, orak arik hingga telur matang.",
          "Masukkan aneka bakso, aduk merata. Tambahkan air secukupnya.",
          "Setelah air mendidih, masukkan mie instan.",
          "Tambahkan bumbu mie, garam, lada, gula, saos sambal, dan kecap secukupnya. Aduk hingga merata dan mie matang.",
          "Taburkan daun bawang dan bawang goreng.",
          "Mie nyemek siap dihidangkan dan disantap!"
        ],
    kalori:1000,
  },
  {
    id: 6,
    title:
      "Bakso Urat",
    image:
      "https://i.pinimg.com/474x/b2/8f/2f/b28f2f027c80ab7e39a6d5a91e780b78.jpg",
        ingredients: [
          "500 gram daging sapi, giling halus",
          "200 gram tepung sagu",
          "2 butir telur",
          "3 sendok makan tepung tapioka",
          "2 sendok teh garam",
          "1 sendok teh merica bubuk",
          "2 sendok makan bawang putih, haluskan",
          "1 sendok makan kecap manis",
          "Air es secukupnya"
        ],
        steps: [
          "Campurkan daging sapi giling, tepung sagu, telur, tepung tapioka, garam, merica bubuk, bawang putih, dan kecap manis dalam satu wadah besar.",
          "Uleni adonan dengan tangan hingga semua bahan tercampur rata.",
          "Tambahkan air es sedikit-sedikit sambil terus diuleni hingga adonan menjadi kenyal dan bisa dipulung.",
          "Ambil sejumput adonan, bulatkan dan beri sedikit tepung sagu pada bagian luar bakso untuk mencegah lengket.",
          "Rebus air dalam panci hingga mendidih.",
          "Setelah air mendidih, masukkan bakso satu per satu. Masak hingga bakso mengapung dan matang.",
          "Angkat bakso dan tiriskan.",
          "Bakso urat siap disajikan sebagai pelengkap bakso kuah atau bakso goreng."
        ],
    kalori:1500,
  },
  {
    id: 7,
    title: "Toppoki Arrasoyow",
    image:
      "https://i.pinimg.com/474x/89/40/02/8940023b742d5362ebee2b4e18368f38.jpg",
    ingredients: [
          "300 gram tteok (cake rice cake), potong-potong",
          "2 sendok makan gochujang (saus cabai Korea)",
          "1 sendok makan gochugaru (serbuk cabai Korea)",
          "2 sendok makan kecap manis",
          "1 sendok makan gula pasir",
          "3 gelas air",
          "1/2 sendok teh minyak wijen",
          "1 zaitun hijau (opsional, sebagai hiasan)",
          "1 lembar nori, potong-potong (opsional, sebagai hiasan)"
        ],
      steps: [
          "Siapkan tteok: Potong tteok menjadi potongan kecil, sekitar 4-5 cm panjangnya.",
          "Rebus tteok dalam air mendidih selama 3-4 menit atau sampai tteok mengapung dan menjadi kenyal. Tiriskan.",
          "Buat saus: Campur gochujang, gochugaru, kecap manis, gula pasir, dan air dalam panci. Aduk rata.",
          "Rebus saus: Panaskan panci dengan saus di atas api sedang. Masak sambil diaduk hingga saus mendidih dan mengental.",
          "Tambahkan tteok: Masukkan tteok ke dalam saus. Aduk rata hingga tteok terbalut oleh saus.",
          "Masak hingga matang: Masak tteok dalam saus hingga tteok menjadi lebih lunak dan saus meresap dengan baik, sekitar 5-7 menit.",
          "Tambahkan minyak wijen: Tambahkan minyak wijen, aduk rata.",
          "Sajikan: Pindahkan Tteokbokki ke piring saji. Hiasi dengan zaitun hijau dan potongan nori jika diinginkan."
        ],      
    kalori:600,
  },
  {
    id: 8,
    title:
      "Dumpling Korea",
    image:
      "https://i.pinimg.com/474x/47/57/f8/4757f8c345321fc09b124c203a73ea76.jpg",
        ingredients: [
            "2 gelas tepung terigu",
            "1/2 sendok teh garam",
            "1 sendok teh minyak wijen",
            "Air secukupnya",
            "250 gram daging sapi cincang",
            "1 gelas tauge, potong-potong",
            "2 wortel, parut halus",
            "3 batang daun bawang, iris halus",
            "3 siung bawang putih, cincang halus",
            "1 sendok teh kecap asin",
            "1/2 sendok teh lada bubuk",
            "1 sendok teh minyak wijen"
          ],
        steps: [
          " Campurkan tepung terigu, garam, dan minyak wijen dalam mangkuk besar.",
          " Tambahkan air sedikit-sedikit sambil terus diaduk hingga adonan menjadi elastis dan tidak lengket.",
          " Istirahatkan adonan selama 30 menit.",
          // "Membuat Isi Dumpling:",
          " Campurkan daging sapi cincang, tauge, wortel, daun bawang, bawang putih, kecap asin, lada bubuk, dan minyak wijen dalam mangkuk. Aduk rata.",
          " Menyiapkan dan Mengisi Kulit Dumpling:",
          " Ambil sejumput adonan kulit dan pipihkan dengan rolling pin.",
          " Letakkan satu sendok makan adonan isi di tengah kulit.",
          " Lipat kulit menjadi dua dan tekan pinggirnya untuk menyatukan.",
          " Gunakan sedikit air di sepanjang pinggiran kulit untuk menyegel dumpling. Tekan dengan jari atau garpu.",
          " Rebus air dalam panci hingga mendidih.",
          " Masukkan dumpling ke air mendidih dan masak hingga dumpling mengapung dan kulitnya menjadi transparan. Tiriskan.",
          "Alternatif: Menggoreng Dumpling:",
          " Panaskan minyak dalam wajan. Goreng dumpling hingga kuning keemasan di kedua sisi.",
          " Sajikan dumpling dengan saus yang diinginkan, seperti saus kecap atau saus pedas."
        ],
    kalori:150,
  },
  {
    "id": 9,
    "title": "Onigiri",
    "image": "https://i.pinimg.com/474x/da/e0/1f/dae01fe98c757e87c5941025bc0b0004.jpg",
    "ingredients": [
      "2 gelas nasi sushi (beras yang cocok untuk membuat sushi)",
      "1/4 gelas cuka beras",
      "2 sendok makan garam",
      "Filling (misalnya: alga nori, salmon panggang, atau umeboshi)"
    ],
    "steps": [
      " Masak nasi sesuai petunjuk di kemasan.",
      " Setelah matang, biarkan nasi dingin.",
      " Campurkan cuka beras dan garam dalam mangkuk kecil, aduk rata.",
      " Panaskan campuran hingga garam larut. Biarkan dingin.",
      " Basahi tangan dengan larutan cuka beras.",
      " Ambil sejumput nasi dan ratakan di telapak tangan yang telah dibasahi.",
      " Letakkan filling di tengah nasi.",
      " Tutup dengan nasi lagi dan bentuk menjadi segitiga atau bulat.",
      " Bungkus Onigiri dengan selembar alga nori jika diinginkan.",
      " Onigiri siap disajikan."
    ],
    "kalori": 10
  },
  {
    "id": 10,
    "title": "Nasi Kuning",
    "image": "https://i.pinimg.com/474x/3d/f7/81/3df78151b37f3a4f958a14a46f0aa357.jpg",
    "ingredients": [
      "2 gelas beras",
      "1 batang serai, memarkan",
      "4 lembar daun jeruk",
      "2 cm lengkuas, memarkan",
      "400 ml santan",
      "1 sendok teh kunyit bubuk",
      "Garam secukupnya",
      "Minyak untuk menumis"
    ],
    "steps": [
      " Panaskan minyak, tumis serai, daun jeruk, dan lengkuas hingga harum.",
      " Tambahkan kunyit bubuk, aduk rata.",
      " Masukkan beras, aduk hingga beras terbalut bumbu.",
      " Tuangkan santan, tambahkan garam secukupnya.",
      " Masak nasi hingga matang dengan metode biasa atau menggunakan rice cooker.",
      " Nasi kuning siap disajikan sebagai pelengkap hidangan Indonesia. Bisa juga dihidangkan dengan lauk-pauk dan acar."
    ],
    "kalori": 800
  },
  {
    id: 11,
    title: "Ikan Bakar Jimbaran",
    image: "https://i.pinimg.com/564x/49/cc/95/49cc955cb1a67fe6e1c396873661c896.jpg",
    ingredients: [
      "Ikan (pilih sesuai selera)",
      "Bumbu Jimbaran",
      "Jeruk nipis",
      "Daun pisang untuk pembungkus"
    ],
    steps: [
      "Bersihkan ikan dan lumuri dengan bumbu Jimbaran. Diamkan selama 30 menit.",
      "Siapkan daun pisang untuk membungkus ikan.",
      "Bakar ikan dalam daun pisang hingga matang dan harum.",
      "Sajikan dengan perasan jeruk nipis."
    ],
    kalori: 600,
  },
  {
    id: 12,
    title: "Capcay Goreng",
    image: "https://i.pinimg.com/564x/b9/c7/18/b9c718b18ad49065c17f54b0f87a1ae2.jpg",
    ingredients: [
      "Brokoli",
      "Wortel",
      "Kol",
      "Bunga kol",
      "Jamur",
      "Ayam suwir",
      "Udang",
      "Bawang putih",
      "Saos tiram",
      "Kecap manis",
      "Merica",
      "Garam"
    ],
    steps: [
      "Rebus sayuran hingga setengah matang. Tiriskan.",
      "Tumis bawang putih hingga harum, masukkan ayam suwir dan udang.",
      "Tambahkan sayuran, aduk rata.",
      "Beri saus tiram, kecap manis, merica, dan garam sesuai selera.",
      "Masak hingga semua bahan matang.",
      "Capcay goreng siap disajikan."
    ],
    kalori: 500,
  },
  {
    id: 13,
    title: "Pisang Goreng Keju",
    image: "https://i.pinimg.com/736x/ee/22/06/ee2206feff17d1976d014d352cc362c0.jpg",
    ingredients: [
      "Pisang raja matang",
      "Tepung terigu",
      "Air es",
      "Keju parut"
    ],
    steps: [
      "Potong pisang menjadi dua bagian.",
      "Campur tepung terigu dengan air es hingga membentuk adonan kental.",
      "Celupkan pisang ke dalam adonan tepung terigu.",
      "Goreng pisang hingga kecoklatan.",
      "Angkat dan taburkan keju parut di atasnya.",
      "Pisang goreng keju siap dinikmati."
    ],
    kalori: 300,
  },
  {
    id: 14,
    title: "Sup Tomat Telur",
    image: "https://i.pinimg.com/564x/6d/39/92/6d3992e6ccf1482a8c240c161e205ca9.jpg",
    ingredients: [
      "Tomat",
      "Bawang putih",
      "Bawang bombay",
      "Kaldu ayam",
      "Telur",
      "Garam",
      "Merica",
      "Daun seledri"
    ],
    steps: [
      "Tumis bawang putih dan bawang bombay hingga harum.",
      "Masukkan tomat yang sudah dipotong kecil-kecil.",
      "Tambahkan kaldu ayam, garam, dan merica.",
      "Kocok telur dan masukkan ke dalam sup sambil diaduk rata.",
      "Tambahkan daun seledri, masak hingga mendidih.",
      "Sup tomat telur siap disajikan."
    ],
    kalori: 150,
  },
  {
    id: 15,
    title: "Rendang Padang",
    image: "https://i.pinimg.com/564x/f6/b0/e4/f6b0e4dd50c73e8b0ae055b9c6d56d6c.jpg",
    ingredients: [
      "Daging sapi",
      "Santan kelapa",
      "Daun jeruk",
      "Serai",
      "Asam kandis",
      "Bumbu rendang Padang"
    ],
    steps: [
      "Rebus daging sapi hingga setengah matang.",
      "Tumis bumbu rendang hingga harum.",
      "Masukkan daging sapi ke dalam tumisan bumbu.",
      "Tambahkan santan kelapa, daun jeruk, serai, dan asam kandis.",
      "Masak hingga daging empuk dan bumbu meresap.",
      "Rendang Padang siap dinikmati."
    ],
    kalori: 800,
  },
  {
    id: 16,
    title: "Pasta Carbonara",
    image: "https://i.pinimg.com/564x/d7/35/82/d73582f134d84e352c73179fae3aa1a8.jpg",
    ingredients: [
      "Spaghetti",
      "Keju parmesan",
      "Susu cair",
      "Cream cheese",
      "Bawang putih",
      "Bacon",
      "Garam",
      "Merica"
    ],
    steps: [
      "Rebus spaghetti hingga al dente.",
      "Tumis bawang putih dan bacon hingga harum.",
      "Campurkan susu cair, cream cheese, dan keju parmesan.",
      "Tambahkan garam dan merica sesuai selera.",
      "Masukkan spaghetti ke dalam saus carbonara.",
      "Pasta carbonara siap disajikan."
    ],
    kalori: 700,
  },
  {
    id: 17,
    title: "Bubur Ayam Spesial",
    image: "https://i.pinimg.com/564x/82/e6/b0/82e6b091954b3f0557adf071731e253b.jpg",
    ingredients: [
      "Beras",
      "Ayam suwir",
      "Bawang goreng",
      "Kecap manis",
      "Ketumbar",
      "Jahe",
      "Telur rebus",
      "Daun seledri"
    ],
    steps: [
      "Rebus beras hingga menjadi bubur.",
      "Tumis bawang putih, jahe, dan ketumbar hingga harum.",
      "Tambahkan ayam suwir dan aduk hingga matang.",
      "Sajikan bubur dengan telur rebus, kecap manis, bawang goreng, dan daun seledri."
    ],
    kalori: 600,
  },
  {
    id: 18,
    title: "Salad Buah Segar",
    image: "https://i.pinimg.com/564x/ad/08/a7/ad08a792cfdb160463d28b0f45c3d03c.jpg",
    ingredients: [
      "Apel",
      "Pisang",
      "Anggur",
      "Strawberry",
      "Kiwi",
      "Yogurt",
      "Madu"
    ],
    steps: [
      "Potong semua buah menjadi ukuran kecil.",
      "Campur buah dalam mangkuk besar.",
      "Tambahkan yogurt dan madu, aduk rata.",
      "Sajikan salad buah segar."
    ],
    kalori: 200,
  },
  {
    id: 19,
    title: "Lalapan Bebek",
    image: "https://i.pinimg.com/564x/39/72/d6/3972d627aa52fca2980e9ec6b54ae456.jpg",
    ingredients: [
      "1 ekor bebek, potong menjadi bagian-bagian",
      "Bumbu rendaman:",
      "3 siung bawang putih, haluskan",
      "1 ruas jahe, parut",
      "1 sendok teh ketumbar bubuk",
      "1 sendok teh garam",
      "1/2 sendok teh lada hitam",
      "Minyak untuk menggoreng"
    ],
    steps: [
      "Campurkan bawang putih, jahe, ketumbar bubuk, garam, dan lada hitam dalam mangkuk untuk membuat bumbu rendaman.",
      "Rendam potongan bebek dalam bumbu tersebut dan diamkan selama minimal 1 jam.",
      "Panaskan minyak dalam wajan hingga cukup panas.",
      "Goreng potongan bebek hingga warnanya kecoklatan dan dagingnya matang sempurna.",
      "Angkat, tiriskan, dan sajikan lalapan bebek dengan sambal atau saus pilihanmu."
    ],
    kalori: 800,
  },  
  {
    id: 20,
    title: "Smoothie Berry",
    image: "https://i.pinimg.com/736x/87/ad/79/87ad791d2fe1d1cc3f88b017a67af60f.jpg",
    ingredients: [
      "Blueberry",
      "Strawberry",
      "Raspberry",
      "Yogurt",
      "Madu",
      "Es batu"
    ],
    steps: [
      "Blender semua buah berry bersama yogurt dan madu.",
      "Tambahkan es batu dan blend hingga halus.",
      "Tuangkan smoothie berry ke dalam gelas.",
      "Nikmati smoothie segar ini!"
    ],
    kalori: 150,
  },
{
  id: 31,
  title: "Salad Ayam Biji Wijen",
  image: "https://img2.beritasatu.com/cache/beritasatu/960x620-3/23062012103616.jpg" ,
  ingredients: [
    "Dada ayam tanpa kulit",
    "Kacang kedelai",
    "Wortel",
    "Daun Bawang",
    "Tomat",
    "Daun ketumbar",
    "Daun kemangi",
    "Biji wijen"
  ],
  steps: [
    "Taruh dada ayam di wajan dan tuang air dingin  ke dalamnya.",
    "taurh kacang kedelai tepat di atas dada ayam kemudian masak selama 8 menit.",
    "campurkan semua bahan untuk dressing di dalam wadah yang besar. ",
    "Aduk perlahan dan pastikan semua bagian terlapisi oleh saus dressing.",
  ],
  kalori: 300,
},
{
  id: 32,
  title: "Risotto Krim Tomat",
  image: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/tomato-mascarpone-risotto-b090efa.jpg?quality=90&webp=true&resize=300,272" ,
  ingredients: [
    "1 liter kaldu sayur",
    "1 blok mentega",
    "1 sendok makan minyak zaitun",
    "1 bawang bombay: cincang halus",
    "2 siung bawang putih; cincang halus",
    "1 tangkai daun rosemary; cincang halus",
    "250 g nasi risotto",
    "300 g tomat ceri; dibelah dua",
    "Sejumput daun basil",
  ],
  steps: [
    "Keluarkan tomat kaleng dan setengah kaldu ke dalam food processor dan olah hingga halus.",
    "Kemudian tuang campuran tersebut ke dalam wajan dengan sisa kaldu buat mendidih di atas api kecil.",
    "mentega dan minyak zaitun di dalam wajan yang lebih besar dan panaskan hingga mentega meleleh. ",
    "Kemudian campurkan bawang bombai, masak selama 6-8 menit hingga lembut.",
    "Setelah itu campurkan bawang putih dan daun rosemary. Masak lagi selama 1 menit.",
    " Setelah itu masukkan nasi risotto dan masak lagi selama 1 menit.",

  ],
  kalori: 381,
},
{
  id: 33,
  title: "Salmon dan Bayam dengan Saus Tartar",
  image: "https://cdn.idntimes.com/content-images/post/20221007/02kitchrex1-master768-bf9a6deddee3e9911ea6ca2ec1a6ee1f_600x400.jpg" ,
  ingredients: [
    "1 sendok teh minyak sayur",
    "2 salmon fillet tanpa kulit",
    "250 g sayur bayam",
    "2 sendok makan krim/saus tartar rendah lemak",
    "ari lemon",
    "2 sendok makan daun peterseli; cincang kasar",
    "Irisan lemon untuk penyajian",
  ],
  steps: [
    "Bumbui salmon pada kedua sisinya.",
    "Goreng selama 4 menit untuk kedua sisi hingga berwarna keemasan dan daging terkelupas dengan mudah.",
    "Petik daun dan batang bayam, masak dengan sedikit minyak, bumbui dan tunggu hingga sedikit layu.",
  ],
  kalori: 381,
},
{
  id: 34,
  title: "Salmon Burger",
  image: "https://www.willcookforsmiles.com/wp-content/uploads/2014/05/Perfect-Salmon-Burger-1-willcookforsmiles.com_.jpg",
  ingredients: [
    "4 salmon fillet tanpa tulang dan kulit; potong kotak-kotak",
    "2 sendok makan pasta kari",
    "Jahe seukuran jempol yang diparut",
    "1 sendok teh soy sauce",
    "1 tangkai daun ketumbar; cincang kasar",
    "1 sendok teh minyak sayur",
    "Irisan lemon; untuk penyajian",

  ],
  steps: [
    "Tuangkan daging salmon yang sudah dipotong ke dalam Food Processor bersama Thai red curry paste, parutan jahe, soy sauce dan daun ketumbar",
    "Proses sampai seluruh campuran tercampur dengan sempurna dan terlihat mudah dibentuk.",
    "Keluarkan campuran tersebut dan bentuk menjadi 4 burger.",
    "Panaskan minya di dalam wajan, kemudian goreng burger selama 4 hingga 5 menit hingga matang pada kedua sisi.",
    "tuang cuka dan gula ke dalam campuran sayuran tersebut dan sajikan dengan burger beserta nasi hangat.",

  ],
  kalori: 292,
},
{
  id: 35,
  title: "Tomat dan Paprika Ham Omelette",
  image: "https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/02/20/2cc144371d142b868fde29e32550283b-75598336.jpg",
  ingredients: [
    "2 butir telur dan 3 putih telur tambahan.",
    "minyak zaitun 1 sdt.",
    "1 paprika merah, dibuang bijinya dan cincang halus.",
    "2 daun bawang, bagian putih dan hijau disimpan terpisah dan cincang halus.",
    "25 g keju cheddar rendah lemak.",
    "roti gandum",
    "1-2 cincang tomat segar sebagai topping.",
  ],
  steps: [
    "Campur seluruh telur di dalam satu wadah.",
    "Bumbui dengan sedikit garam dan lada hitam.",
    "Panaskan minyak di dalam wajan anti lengket dan masak paprika merah selama 3-4 menit.",
    "Buang bagian putih dari daun bawang dan masak selama 1 menit setelahnya.",
    "Tuangkan telur dan masak hingga matang.",
    "taburkan potongan daging ham dan keju cheddar di atas permukaan telur.",
    "beri taburan daun bawang, potongan tomat dan nikmati selagi hangat bersama roti gandum Anda.",

  ],
  kalori: 206,
},
{
  id: 36,
  title: "Perkedel Telur",
  image: "https://img-global.cpcdn.com/recipes/b0a8ed155ef69ba0/640x640sq70/photo.webp",
  ingredients: [
    "5 butir telur ayam, rebus, kupas, belah dua.",
    "25 gram tepung tapioka",
    "150 gram jamur merang, cincang",
    "Sejumput garam",
    "2 butir bawang merah",
    "1 siung bawang putih",
    "1 sdt lada",
    "1 sdt garam"
  ],
  steps: [
    "Belah dua telur rebus dan ambil kuningnya lalu haluskan.",
    "Campur cincangan telur ayam, jamur merang, tepung tapioka, bumbu halus, dan kuning telur.",
    "Bagi adonan menjadi sepuluh bagian dan bentuk sesuai selera.",
    "Panaskan minyak, goreng hingga berwarna kuning kecokelatan lalu angkat.",
    "Makanan siap disajikan."
  ],
  kalori: 213,
},  
{
id: 37,
title: "Sayur tahu jamur rumput laut",
image: "https://img-global.cpcdn.com/recipes/9ea9854133c33d12/640x640sq70/photo.webp",
ingredients: [
  "150 gram tahu putih, potong dadu sedang.",
  "50 gram rumput laut",
  "100 gram jamur segar",
  "400 ml kaldu ayam",
  "1 buah tomat, potong jadi 4",
  "1 siung bawang putih",
  "1 sdt lada",
  "1 sdm minyak goreng untuk menumis",
  "1 sdm bawang putih, cincang",
  "1 ruas jahe, cincang",
  "Sejumput garam",
  "1 sdt kecap asin",

],
steps: [
  "Panaskan 1 sdm minyak di panci kecil, masukkan jahe dan bawang putih cincang. Tumis hingga aromanya keluar.",
  "Tuang kaldu di panci, didihkan. Masukkan tahu, jamur, tomat, rumput laut, garam, dan kecap. Didihkan kembali lalu angkat.",
  "Maknan siap dihidangkan.",
],
kalori: 120,
},  
{
id: 38,
title: "Tumis genjer",
image: "https://img-global.cpcdn.com/recipes/a78cd7fdb664f9dd/640x640sq70/photo.webp",
ingredients: [
  "Irisan tipis 2 sdm bawang merah.",
  "Irisan tipis 1 sdm bawang putih",
  "1 sdt terasi",
  "Irisan bulat 2 sdm cabai merah, buang isinya",
  "Irisan bulat 2 sdm cabai hijau, buang isinya",
  "1 ruas lengkuas",
  "2 lembar daun salam",
  "1 sdm garam",
],
steps: [
  "Panaskan 2 sdm minyak dan tumis irisan bawang merah dan bawang putih hingga layu dan aromanya keluar.",
  "Masukkan irisan bulat cabai merah, cabai hijau, terasi, garam, irisan lengkuas, daun salam, dan garam. Tumis kembali sampai layu.",
  "Masukkan potongan bunga genjer, tumis selama 5 menit hingga lalu, angkat.",
  "Hidangkan tumis genjer selagi hangat."
],
kalori: 77,
},  
{
id: 39,
title: "Rendang kentang",
image: "https://img-global.cpcdn.com/recipes/7ed7bcf56f654faf/640x640sq70/photo.webp",
ingredients: [
  "500 gram kentang mini, bersihkan dan cuc.",
  "400 ml santan kental",
  "50 gram kelapa parut",
  "2 sdm minyak untuk menumis",
  "3 butir bawang merah",
  "2 siung bawang putih",
  "3 buah cabai merah",
  "1 butir kemiri",
  "1 sdt ketumbar",
  "1 sdm garam",
  "1 sdm lengkuas",

],
steps: [
  "Panaskan minyak di wajan anti lengket.",
  "Tuangi santan masak dengan api sedang hingga mendidih.",
  "Beri parutan kelapa yang sudah disangrai tumis sejenak di atas api sampai parutan kelapa dan bumbu tercampur rata dengan kentang.",
],
kalori: 195,
},  
{
id: 40,
title: "Sayur labu siam",
image: "https://cdn-brilio-net.akamaized.net/webp/news/2022/03/24/225766/1700080-resep-sayur-santan-labu-siam.jpg",
ingredients: [
  "400 gram labu siam setengah tua, kupas dan iris korek api.",
  "700 ml santan.",
  "2 sdm minyak untuk menumis.",
  "2 siung bawang putih.",
  "3 butir bawang merah.",
  "Kunyit.",
  "3 butir kemiri",
  "1 sdt ketumbar",
  "1 sdm garam ",
  "1 sdt irisan gula merah",
],
steps: [
  "Labu siam yang sudah diiris diberi garam dan hancurkan selama 10 menit kemudian cuci dan tiriskan.",
  "Panaskan minyak dan tumis bumbu halus hingga harum.",
  "Tuang santan lalu masak hingga matang dan bumbu meresap.",
],
kalori: 108,
},
];
export default resep;
